language: python
python:
  - "3.6"
#sudo: false

install:
  - pip install -r requirements.txt

script:
  - pytest

#notifications:
#  email:
#    recipients:
#    - katya.grohotova.4@gmail.com
#    on_success: always
#    on_failure: always